ktor:
    development: true
    application:
        modules:
            - com.restuu.presentation.ApplicationKt.module
    deployment:
        port: "$PORT:8080"
        watches: [ classes, resources ]
